# Generated by Django 2.2.5 on 2019-09-30 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Armory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('part_number', models.CharField(max_length=200)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='NWA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nwa', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'NWA',
                'verbose_name_plural': 'NWAs',
            },
        ),
        migrations.CreateModel(
            name='POC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('commercial', models.EmailField(max_length=100)),
                ('dsn', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('complete', models.DateTimeField(blank=True, null=True)),
                ('quote_number', models.CharField(blank=True, max_length=100)),
                ('user_manual', models.FileField(blank=True, null=True, upload_to='')),
                ('size_width', models.FloatField(blank=True, null=True)),
                ('side_depth', models.FloatField(blank=True, null=True)),
                ('size_height', models.FloatField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('armory', models.ManyToManyField(blank=True, to='quotes.Armory')),
                ('comment', models.ManyToManyField(blank=True, to='quotes.Comment')),
                ('image', models.ManyToManyField(blank=True, to='quotes.Image')),
                ('note', models.ManyToManyField(blank=True, to='quotes.Note')),
                ('nwa', models.ManyToManyField(blank=True, to='quotes.NWA')),
                ('poc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.POC')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Project')),
                ('serial_number', models.ManyToManyField(blank=True, to='quotes.SerialNumber')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('component', models.ManyToManyField(to='quotes.Component')),
            ],
        ),
        migrations.AddField(
            model_name='armory',
            name='component_qty',
            field=models.ManyToManyField(to='quotes.ComponentQty'),
        ),
    ]
