# Generated by Django 2.2.5 on 2019-09-30 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmoryComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Component')),
            ],
        ),
        migrations.RemoveField(
            model_name='armory',
            name='component_qty',
        ),
        migrations.DeleteModel(
            name='ComponentQty',
        ),
        migrations.AddField(
            model_name='armory',
            name='armory_components',
            field=models.ManyToManyField(to='quotes.ArmoryComponent'),
        ),
    ]
