# Generated by Django 2.2.5 on 2019-09-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20190930_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armory',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
