# Generated by Django 2.2.5 on 2019-09-30 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20190930_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='armory',
            new_name='armorys',
        ),
    ]
