# Generated by Django 2.2.5 on 2019-09-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_auto_20190930_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
