# Generated by Django 2.2.5 on 2019-10-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_auto_20190930_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='side_depth',
            new_name='size_depth',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='user_manual',
        ),
        migrations.AddField(
            model_name='armory',
            name='user_manual',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
